Vagrant.configure("2") do |config|
  config.vm.box = "centos/7"
  config.vm.provider "virtualbox" do |vb|
     vb.memory = "2048"
     vb.cpus = 4
  end
  config.vm.provision "shell", path: "bootstrap.sh"
end