# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
Vagrant.configure("2") do |config|
  # The most common configuration options are documented and commented below.
  # For a complete reference, please see the online documentation at
  # https://docs.vagrantup.com.

  # Every Vagrant development environment requires a box. You can search for
  # boxes at https://vagrantcloud.com/search.
  config.vm.box = "centos/7"

  config.vm.define "nfsserver" do |nfsserver|
    nfsserver.vm.hostname = "nfsserver.example.com"
    nfsserver.vm.network "private_network", ip: "192.168.33.25"
    nfsserver.vm.provision "shell", path: "init-nfs-server.sh"
    nfsserver.vm.synced_folder "resource", "/share", create: true, owner: "root", group: "root", mount_options: ["dmode=755","fmode=644"], type: "rsync"
  end

  config.vm.define "group1" do |group1|
    group1.vm.hostname = "group1"
    group1.vm.network "private_network", ip: "192.168.33.11"
    group1.vm.provision "shell", path: "bootstrap.sh"
  end

  config.vm.define "group2" do |group2|
    group2.vm.hostname = "group2"
    group2.vm.network "private_network", ip: "192.168.33.12"
    group2.vm.provision "shell", path: "bootstrap.sh"
  end

  config.vm.define "group3" do |group3|
    group3.vm.hostname = "group3"
    group3.vm.network "private_network", ip: "192.168.33.13"
    group3.vm.provision "shell", path: "bootstrap.sh"
  end

  config.vm.define "group4" do |group4|
    group4.vm.hostname = "group4"
    group4.vm.network "private_network", ip: "192.168.33.14"
    group4.vm.provision "shell", path: "bootstrap.sh"
  end

  config.vm.define "peer0org1" do |peer0org1|
    peer0org1.vm.hostname = "peer0-org1.example.com"
    peer0org1.vm.network "private_network", ip: "192.168.33.21"
    peer0org1.vm.provision "shell", path: "bootstrap.sh"
  end

  config.vm.define "peer1org1" do |peer1org1|
    peer1org1.vm.hostname = "peer1-org1.example.com"
    peer1org1.vm.network "private_network", ip: "192.168.33.22"
    peer1org1.vm.provision "shell", path: "bootstrap.sh"
  end

  config.vm.define "peer0org2" do |peer0org2|
    peer0org2.vm.hostname = "peer0-org2.example.com"
    peer0org2.vm.network "private_network", ip: "192.168.33.23"
    peer0org2.vm.provision "shell", path: "bootstrap.sh"
  end

  config.vm.define "peer1org2" do |peer1org2|
    peer1org2.vm.hostname = "peer1-org2.example.com"
    peer1org2.vm.network "private_network", ip: "192.168.33.24"
    peer1org2.vm.provision "shell", path: "bootstrap.sh"
  end

  # Disable automatic box update checking. If you disable this, then
  # boxes will only be checked for updates when the user runs
  # `vagrant box outdated`. This is not recommended.
  # config.vm.box_check_update = false

  # Create a forwarded port mapping which allows access to a specific port
  # within the machine from a port on the host machine. In the example below,
  # accessing "localhost:8080" will access port 80 on the guest machine.
  # NOTE: This will enable public access to the opened port
  # config.vm.network "forwarded_port", guest: 80, host: 8080

  # Create a forwarded port mapping which allows access to a specific port
  # within the machine from a port on the host machine and only allow access
  # via 127.0.0.1 to disable public access
  # config.vm.network "forwarded_port", guest: 80, host: 8080, host_ip: "127.0.0.1"

  # Create a private network, which allows host-only access to the machine
  # using a specific IP.
  # config.vm.network "private_network", ip: "192.168.33.10"

  # Create a public network, which generally matched to bridged network.
  # Bridged networks make the machine appear as another physical device on
  # your network.
  # config.vm.network "public_network"

  # Share an additional folder to the guest VM. The first argument is
  # the path on the host to the actual folder. The second argument is
  # the path on the guest to mount the folder. And the optional third
  # argument is a set of non-required options.
  # config.vm.synced_folder "../data", "/vagrant_data"

  # Provider-specific configuration so you can fine-tune various
  # backing providers for Vagrant. These expose provider-specific options.
  # Example for VirtualBox:
  #
  # config.vm.provider "virtualbox" do |vb|
  #   # Display the VirtualBox GUI when booting the machine
  #   vb.gui = true
  #
  #   # Customize the amount of memory on the VM:
  #   vb.memory = "1024"
  # end
  #
  # View the documentation for the provider you are using for more
  # information on available options.

  # Enable provisioning with a shell script. Additional provisioners such as
  # Puppet, Chef, Ansible, Salt, and Docker are also available. Please see the
  # documentation for more information about their specific syntax and use.
  # config.vm.provision "shell", inline: <<-SHELL
  #   apt-get update
  #   apt-get install -y apache2
  # SHELL
end
